version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: 214748
      POSTGRES_DB: big_data
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - ./data:/data
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
